### ISSUE TITLE
Prevent error when piping to grep and head. 

### ISSUE THREAD

**Issue by bostrt** [kxr/o-must-gather#23]
```
$ omg logs machine-config-daemon-fsq2m -c machine-config-daemon  | grep 'content mismatch' | head 
2020-12-05T05:43:27.410179702Z E1205 05:43:27.407869    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:43:29.455216522Z E1205 05:43:29.455169    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:43:37.500319093Z E1205 05:43:37.500238    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:43:53.562228581Z E1205 05:43:53.562169    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:44:25.616800164Z E1205 05:44:25.616761    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:45:25.67432268Z E1205 05:45:25.674259    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:46:25.729651363Z E1205 05:46:25.729575    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:47:25.794216204Z E1205 05:47:25.793687    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:48:25.83906723Z E1205 05:48:25.839025    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
2020-12-05T05:49:25.889781945Z E1205 05:49:25.889719    2237 daemon.go:1350] content mismatch for file /etc/kubernetes/kubelet-ca.crt: -----BEGIN CERTIFICATE-----
Traceback (most recent call last):
  File "/home/rdu/rbost/.local/bin/omg", line 11, in <module>
    load_entry_point('o-must-gather==1.0.1', 'console_scripts', 'omg')()
  File "/home/rdu/rbost/.local/lib/python3.6/site-packages/omg/cli.py", line 77, in main
    func(args)
  File "/home/rdu/rbost/.local/lib/python3.6/site-packages/omg/cmd/log.py", line 74, in log
    print(ol.read())
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by bostrt** [comment]
I'll follow-up with a PR for this issue tonight or tomorrow.

**Comment by bostrt** [comment]
FTR looks like this is still an issue in latest version. I had just realized been testing on 1.0.1.
