### ISSUE TITLE
"omg describe <resource>" fails

### ISSUE THREAD

**Issue by dciancio** [kxr/o-must-gather#43]
Using the following python3-click module included with Fedora:
python3-click-7.1.2-3.fc33.noarch

Trying the following command and getting this error.  Whether I try describing any resource, I get the same error everytime.
f7ac15/extracted-machine-configs$ omg describe co
Traceback (most recent call last):
  File "/usr/local/bin/omg", line 33, in <module>
    sys.exit(load_entry_point('o-must-gather==1.2.3', 'console_scripts', 'omg')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: describe_cmd() got an unexpected keyword argument 'object'

Thanks!

**Comment by kxr** [comment]
@dciancio  Thank you for reporting this issue. The `describe` feature is still underdevelopment. There is a type causing this exception. Once fixed it will just display the message "This feature is not yet developed!"
